/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Amiani
 */
public class PageThree extends javax.swing.JFrame {

    /**
     * Creates new form PageThree
     */
    public PageThree() {
        initComponents();
        Connect();
        AutoCompleteDecorator.decorate(ItemsInComboBox);
        
        this.setTitle("Store Wise 1.0");
    setIconImage(); //create method and go down the page
        
    }
      
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con =(Connection) (com.mysql.cj.jdbc.ConnectionImpl) DriverManager.getConnection("jdbc:mysql://localhost/storerecords2","root","12345678");
                String sql = "select * from itemsin";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet r = ps.executeQuery();
                intable.setModel(DbUtils.resultSetToTableModel(r));
                intable.setEnabled(false);
                
                intable.getColumnModel().getColumn(0).setPreferredWidth(5);
                intable.getColumnModel().getColumn(1).setPreferredWidth(90);
                intable.getColumnModel().getColumn(2).setPreferredWidth(90);
                intable.getColumnModel().getColumn(3).setPreferredWidth(50);
                intable.getColumnModel().getColumn(4).setPreferredWidth(8);
                intable.getColumnModel().getColumn(5).setPreferredWidth(90);
  
                
                intable.getTableHeader().setResizingAllowed(false);
            } catch (SQLException ex) {
                Logger.getLogger(PageThree.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PageThree.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ItemsInComboBox = new javax.swing.JComboBox<>();
        txtPersonIn = new javax.swing.JTextField();
        txtPhoneIn = new javax.swing.JTextField();
        txtAmountIn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        intable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 51));
        jLabel6.setText("ACK SIGOWET SECONDARY SCHOOL STORE RECORDS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("ACK SIGOWET SECONDARY SCHOOL STORE RECORDS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ITEM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PERSON");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PHONE NO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("AMOUNT");

        ItemsInComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ItemsInComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Ex Books Single Ruled 200Pgs", "Ex Books Square Ruled 200Pgs", "S1", "S2", "Inventory Book", "Counter Book- 1 Quire -96 Pgs", "Counter Book- 2 Quire -192 Pgs", "Counter Book- 3 Quire -288Pgs", "Counter Book- 4 Quire -384 Pgs", "Mark BookV- 2 Quire", "Graph Paper - Reams", "Photocopy Paper", "Fullscap(Ruled)", "Mannilla Papers", "Carbon Papers (100 Sheets)", "Masking Tape", "Cellotape", "White out-20ml", "Office glue", "Stamp pad ink", "White board Marker ink", "Staple pins-24/6", "Thumb Tack", "Office pins", "Stamp Pad", "Spring File", "Box File", "Copy Printer Master-DX2430", "Copy Printer Ink-DX2430", "Grand In Aid", "Marker Pen", "Ledger Book- 2 Quire", "Ledger Book- 1 Quire", "Permanent Marker", "Polythene Paper", "Pencil (HB)", "Class Register", "Official Reciepts", "Ruler", "Rubber", "Ruler", "Tonner Kit", "Blue Pen", "Red Pen", "Black Pen", "Duster", "Envelopes (A5)", "Envelopes (A4)", "Envelopes (DL)", "Epson Printer Ink", "Fee Register", "L.P.O (Printed)", "Staple Pins -23/12", "Tonner TK - Universal", "Stapler-DP-520", "Stapler-DP-210", "Paper Punch-540", "School Rubber Stamp", "Calculator (Electronic)", "Maize", "Beans", "Millet", "Sorghum", "Rice 50kg Bag", "Sugar 50kg Bag", "Royco/Oyo", "Tea Leaves- 500g", "Salt-500g", "Cooking Oil-20L", "Soap", "Steel Wool", "Scouring Pad" }));
        ItemsInComboBox.setToolTipText("Select an Item");

        txtPersonIn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtPersonIn.setToolTipText("Type in Name");

        txtPhoneIn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtPhoneIn.setToolTipText("Type in Phone NO");
        txtPhoneIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneInKeyTyped(evt);
            }
        });

        txtAmountIn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtAmountIn.setToolTipText("Type in Amount");
        txtAmountIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountInKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("BACK");
        jButton1.setToolTipText("Back to Main Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        intable.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        intable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ITEM", "PERSON", "PHONE NO", "AMOUNT", "DATE/TIME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(intable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("ITEMS IN RECORDS");

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.setToolTipText("Submit Records After Typing in Every Field");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel8.setText("Store Wise V1.0 By Brian Kigen 0717262560 kigenbrian617@gmail.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(345, 345, 345))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(199, 199, 199))))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhoneIn, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(txtAmountIn)
                    .addComponent(txtPersonIn)
                    .addComponent(ItemsInComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(ItemsInComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtPersonIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPhoneIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtAmountIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
          // TODO add your handling code here:
        String selectedText = (String) ItemsInComboBox.getSelectedItem();
        String Supplier = txtPersonIn.getText();
        String PhoneIn = txtPhoneIn.getText();
        String AmountIn = txtAmountIn.getText();
        
         if (selectedText.equals("<Select>")) {
            JOptionPane.showMessageDialog(this, "Please select an item.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Supplier.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert a name.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (PhoneIn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert a phone number.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (AmountIn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert an amount.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
        
        pst = con.prepareStatement("insert into itemsin(item,Supplier,PhoneNo,Amount)values(?,?,?,?)");
        
        pst.setString(1,selectedText);
        pst.setString(2,Supplier);
        pst.setString(3,PhoneIn);
        pst.setString(4,AmountIn);
        
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(this,"Record Added");
        
        txtPersonIn.setText("");
        txtPhoneIn.setText("");
        txtAmountIn.setText("");
        
        ItemsInComboBox.setSelectedItem("<Select>");
        
        refreshItemsInTable();
        
        }
        } catch (SQLException ex) {
            
            
              ex.printStackTrace(); // Prints the error stack trace to the console
              JOptionPane.showMessageDialog(null, "ERROR!: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
              
              
            
            Logger.getLogger(PageThree.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
      
      private void refreshItemsInTable() {
    try {
        DefaultTableModel model = (DefaultTableModel) intable.getModel();
        model.setRowCount(0); // Clear existing data from the table
        
        // Retrieve the latest data from the database and add it to the table
        String query = "SELECT * FROM itemsin";
        pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        
        // Iterate through the result set and add the data to the table model
        while (rs.next()) {
            String id = rs.getString("id");
            String item = rs.getString("item");
            String Supplier = rs.getString("Supplier");
            String phoneNo = rs.getString("PhoneNo");
            String amount = rs.getString("Amount");
            String dateAndTime = rs.getString("Date_and_time");
            
            // Add the data to the table model
            model.addRow(new Object[] {id,item, Supplier, phoneNo, amount,dateAndTime});
        }
        
        rs.close(); // Close the result set
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "ERROR!: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPhoneInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneInKeyTyped
        // TODO add your handling code here:
        
         char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneInKeyTyped

    private void txtAmountInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountInKeyTyped
        // TODO add your handling code here:
        
         char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtAmountInKeyTyped

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(PageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(PageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(PageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(PageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            PageThree PageThree = new PageThree();
            
            // Set the size of the frame
            PageThree.setSize(1050, 550);

            // Get the dimensions of the screen
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

            // Calculate the position of the frame to center it on the screen
            int xPos = (screenSize.width - PageThree.getWidth()) / 2;
            int yPos = (screenSize.height - PageThree.getHeight()) / 2;

            // Set the position of the frame
            PageThree.setLocation(xPos, yPos);
            
            PageThree.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ItemsInComboBox;
    private javax.swing.JTable intable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAmountIn;
    private javax.swing.JTextField txtPersonIn;
    private javax.swing.JTextField txtPhoneIn;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconPNG.png")));
    }
}
