/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Amiani
 */
public class PageTwo extends javax.swing.JFrame {

    /**
     * Creates new form PageTwo
     */
    public PageTwo() {
        initComponents();
        Connect();
        AutoCompleteDecorator.decorate(ItemsOutComboBox);
        
        this.setTitle("Store Wise 1.0");
    setIconImage(); //create method and go down the page
        
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con =(Connection) (com.mysql.cj.jdbc.ConnectionImpl) DriverManager.getConnection("jdbc:mysql://localhost/storerecords2","root","12345678");
                String sql = "select * from itemsout";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                outtable.setModel(DbUtils.resultSetToTableModel(rs));
                outtable.setEnabled(false);
                
                outtable.getColumnModel().getColumn(0).setPreferredWidth(5);
                outtable.getColumnModel().getColumn(1).setPreferredWidth(90);
                outtable.getColumnModel().getColumn(2).setPreferredWidth(90);
                outtable.getColumnModel().getColumn(3).setPreferredWidth(50);
                outtable.getColumnModel().getColumn(4).setPreferredWidth(8);
                outtable.getColumnModel().getColumn(5).setPreferredWidth(90);
                
                
                outtable.getTableHeader().setResizingAllowed(false);
            } catch (SQLException ex) {
                
                 ex.printStackTrace(); // Prints the error stack trace to the console
                 JOptionPane.showMessageDialog(null, "SQL Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                
                Logger.getLogger(PageTwo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PageTwo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ItemsOutComboBox = new javax.swing.JComboBox<>();
        txtPersonOut = new javax.swing.JTextField();
        txtPhoneOut = new javax.swing.JTextField();
        txtAmountOut = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outtable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 51));
        jLabel6.setText("ACK SIGOWET SECONDARY SCHOOL STORE RECORDS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ITEM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PERSON");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PHONE NO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("AMOUNT");

        ItemsOutComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ItemsOutComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Ex Books Single Ruled 200Pgs", "Ex Books Square Ruled 200Pgs", "S1", "S2", "Inventory Book", "Counter Book- 1 Quire -96 Pgs", "Counter Book- 2 Quire -192 Pgs", "Counter Book- 3 Quire -288Pgs", "Counter Book- 4 Quire -384 Pgs", "Mark BookV- 2 Quire", "Graph Paper - Reams", "Photocopy Paper", "Fullscap(Ruled)", "Mannilla Papers", "Carbon Papers (100 Sheets)", "Masking Tape", "Cellotape", "White out-20ml", "Office glue", "Stamp pad ink", "White board Marker ink", "Staple pins-24/6", "Thumb Tack", "Office pins", "Stamp Pad", "Spring File", "Box File", "Copy Printer Master-DX2430", "Copy Printer Ink-DX2430", "Grand In Aid", "Marker Pen", "Ledger Book- 2 Quire", "Ledger Book- 1 Quire", "Permanent Marker", "Polythene Paper", "Pencil (HB)", "Class Register", "Official Reciepts", "Ruler", "Rubber", "Ruler", "Tonner Kit", "Blue Pen", "Red Pen", "Black Pen", "Duster", "Envelopes (A5)", "Envelopes (A4)", "Envelopes (DL)", "Epson Printer Ink", "Fee Register", "L.P.O (Printed)", "Staple Pins -23/12", "Tonner TK - Universal", "Stapler-DP-520", "Stapler-DP-210", "Paper Punch-540", "School Rubber Stamp", "Calculator (Electronic)", "Maize", "Beans", "Millet", "Sorghum", "Rice 50kg Bag", "Sugar 50kg Bag", "Royco/Oyo", "Tea Leaves- 500g", "Salt-500g", "Cooking Oil-20L", "Soap", "Steel Wool", "Scouring Pad" }));
        ItemsOutComboBox.setToolTipText("Select an Item");

        txtPersonOut.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtPersonOut.setToolTipText("Type in a name");

        txtPhoneOut.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        txtPhoneOut.setToolTipText("Type in Phone No or ADM No");
        txtPhoneOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneOutKeyTyped(evt);
            }
        });

        txtAmountOut.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtAmountOut.setToolTipText("Type in an Amount");
        txtAmountOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountOutKeyTyped(evt);
            }
        });

        outtable.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        outtable.setSurrendersFocusOnKeystroke(true);
        outtable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(outtable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("ITEMS OUT RECORDS");

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("BACK");
        jButton1.setToolTipText("Go back to main page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.setToolTipText("Submit  Records after Typing in all Fields");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel8.setText("Store Wise V1.0 By Brian Kigen 0717262560 kigenbrian617@gmail.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPersonOut, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmountOut, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhoneOut, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemsOutComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(337, 337, 337))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ItemsOutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPersonOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPhoneOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAmountOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addComponent(jLabel8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try{
        // TODO add your handling code here:
        String selectedText = (String) ItemsOutComboBox.getSelectedItem();
        String PersonOut = txtPersonOut.getText();
        String PhoneOut = txtPhoneOut.getText();
        String AmountOut = txtAmountOut.getText();
        
         if (selectedText.equals("<Select>")) {
            JOptionPane.showMessageDialog(this, "Please select an item.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (PersonOut.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert a name.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (PhoneOut.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert a phone number.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (AmountOut.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please insert an amount.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
        
        pst = con.prepareStatement("insert into itemsout(item,Person,PhoneNo,Amount)values(?,?,?,?)");
        
        pst.setString(1,selectedText);
        pst.setString(2,PersonOut);
        pst.setString(3,PhoneOut);
        pst.setString(4,AmountOut);
        
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(this,"Record Added");
        
        txtPersonOut.setText("");
        txtPhoneOut.setText("");
        txtAmountOut.setText("");
        
        ItemsOutComboBox.setSelectedItem("<Select>");
        
        refreshItemsOutTable(); // Refresh the Items Out table
        
        }
        } catch (SQLException ex) {
            
              ex.printStackTrace(); // Prints the error stack trace to the console
              JOptionPane.showMessageDialog(null, "ERROR!: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
              
            Logger.getLogger(PageTwo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void refreshItemsOutTable() {
    try {
        DefaultTableModel model = (DefaultTableModel) outtable.getModel();
        model.setRowCount(0); // Clear existing data from the table
        
        // Retrieve the latest data from the database and add it to the table
        String query = "SELECT * FROM itemsout";
        pst = con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        
        // Iterate through the result set and add the data to the table model
        while (rs.next()) {
            String id = rs.getString("id");
            String item = rs.getString("item");
            String person = rs.getString("Person");
            String phoneNo = rs.getString("PhoneNo");
            String amount = rs.getString("Amount");
            String dateAndTime = rs.getString("Date_and_time");
            
            // Add the data to the table model
            model.addRow(new Object[] {id,item, person, phoneNo, amount,dateAndTime});
        }
        
        rs.close(); // Close the result set
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "ERROR!: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPhoneOutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneOutKeyTyped
        // TODO add your handling code here:
        // not accept letters
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneOutKeyTyped

    private void txtAmountOutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountOutKeyTyped
        // TODO add your handling code here:
        
         char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtAmountOutKeyTyped

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(PageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(PageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(PageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(PageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            PageTwo PageTwo = new PageTwo();
            
            // Set the size of the frame
            PageTwo.setSize(1050, 550);

            // Get the dimensions of the screen
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

            // Calculate the position of the frame to center it on the screen
            int xPos = (screenSize.width - PageTwo.getWidth()) / 2;
            int yPos = (screenSize.height - PageTwo.getHeight()) / 2;

            // Set the position of the frame
            PageTwo.setLocation(xPos, yPos);
            
            PageTwo.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ItemsOutComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable outtable;
    private javax.swing.JTextField txtAmountOut;
    private javax.swing.JTextField txtPersonOut;
    private javax.swing.JTextField txtPhoneOut;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconPNG.png")));
    }
}
